modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="optimized_fullbright"
version="${version}"
displayName="Optimized Fullbright"
authors="ray"

description='''
Fullbright mod that disables the lighting system to improve performance.
'''

logoFile = "assets/optimizedfullbright/icon.png"
[[dependencies.optimizedfullbright]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.167,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.optimizedfullbright]]
    modId="minecraft"
    type="required"
    versionRange="[21.6,)"
    ordering="NONE"
    side="BOTH"
[[mixins]]
config="optimized_fullbright.mixins.json"

["badoptimizations:incompatibilities"]
options = [
    "enable_sky_color_caching",
    "enable_lightmap_caching"
]
